In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Users\elara\Desktop\Darkom.ma\Data\darkom-annonces-6a0a532a16460470060059.csv")

In [ ]:
df.head()

,annonce_id,date_publication,titre,ville,quartier,type_bien,transaction,prix,surface,nb_chambres,nb_salles_bain,etage,annee_construction
0,ANO000343,2023-05-05,Terrain moderne Meknès,Meknès,Hamria,Terrain,Vente,811401.04,314.40,0.0,NaN,0.0,2014.0
1,ANO001296,2023-08-20,Terrain moderne Kenitra,Kenitra,Centre,Terrain,Location,3843.55,36.46,0.0,0.0,NaN,2008.0
2,ANO001212,2023-06-20,Appartement moderne Oujda,Oujda,Hay Qods,Appartement,Location,9190.70,95.54,2.0,2.0,NaN,2012.0
3,ANO001000,2024-01-21,Appartement à vente - Tanger,Tanger,NaN,Appartement,Vente,30000.00,93.35,1.0,1.0,3.0,2008.0
4,ANO001123,2024-03-19,Beau Villa Rabat,Rabat,Souissi,Villa,Location,20844.72,264.22,3.0,1.0,0.0,2006.0

In [ ]:
df.tail()

,annonce_id,date_publication,titre,ville,quartier,type_bien,transaction,prix,surface,nb_chambres,nb_salles_bain,etage,annee_construction
1503,ANO000592,2024-10-22,Appartement moderne Agadir,Agadir,Hay Mohammadi,Appartement,Vente,573352.89,66.44,3.0,1.0,1.0,1999.0
1504,ANO001157,2024-01-05,Appartement à location - Marrakech,Marrakech,Hivernage,Appartement,Location,1981.82,79.53,4.0,3.0,3.0,2009.0
1505,ANO000333,2023-08-30,Beau Bureau Agadir,Agadir,Hay Mohammadi,Bureau,Vente,1919074.61,145.63,0.0,0.0,0.0,2005.0
1506,ANO001089,2024-06-05,Villa 405m² Ain Diab,Casablanca,Ain Diab,Villa,Location,10130.83,405.30,5.0,3.0,NaN,1986.0
1507,ANO001290,2024-02-23,Beau Appartement Fès,Fès,Medina,Appartement,Vente,748434.07,88.50,3.0,2.0,1.0,2014.0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1508 entries, 0 to 1507
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   annonce_id          1508 non-null   str
 1   date_publication    1432 non-null   str
 2   titre               1508 non-null   str
 3   ville               1508 non-null   str
 4   quartier            1093 non-null   str
 5   type_bien           1470 non-null   str
 6   transaction         1470 non-null   str
 7   prix                1508 non-null   float64
 8   surface             1508 non-null   float64
 9   nb_chambres         1379 non-null   float64
 10  nb_salles_bain      1404 non-null   float64
 11  etage               1276 non-null   float64
 12  annee_construction  1304 non-null   float64
dtypes: float64(6), str(7)
memory usage: 153.3 KB

In [ ]:
df.shape

(1508, 13)

In [ ]:
df.describe()

,prix,surface,nb_chambres,nb_salles_bain,etage,annee_construction
count,1.508000e+03,1508.000000,1379.000000,1404.000000,1276.000000,1304.000000
mean,1.725599e+06,175.810093,2.652647,1.538462,1.926332,2007.045245
std,6.235344e+06,264.165044,2.649947,1.362078,2.450942,10.726143
min,1.200000e+02,8.000000,0.000000,0.000000,0.000000,1961.000000
25%,1.154916e+04,79.882500,1.000000,1.000000,0.000000,2001.000000
50%,6.055835e+05,109.805000,3.000000,1.000000,1.000000,2008.000000
75%,1.819007e+06,218.205000,4.000000,2.000000,3.000000,2014.000000
max,8.000000e+07,3000.000000,25.000000,13.000000,10.000000,2024.000000

In [ ]:
df.columns

Index(['annonce_id', 'date_publication', 'titre', 'ville', 'quartier',
       'type_bien', 'transaction', 'prix', 'surface', 'nb_chambres',
       'nb_salles_bain', 'etage', 'annee_construction'],
      dtype='str')

In [ ]:
df["etage"].unique()

array([ 0., nan,  3.,  4.,  1.,  8.,  7.,  2.,  5.,  6., 10.,  9.])

In [ ]:
df['annonce_id'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1503    False
1504    False
1505    False
1506    False
1507    False
Name: annonce_id, Length: 1508, dtype: bool

In [ ]:
df["nb_salles_bain"].value_counts()

nb_salles_bain
2.0     484
1.0     433
0.0     276
3.0     177
4.0      21
13.0      5
10.0      5
9.0       2
11.0      1
Name: count, dtype: int64

In [ ]:
df["prix"].value_counts().sort_values(ascending=False).head(20)

prix
60000000.00    7
30000.00       6
80000000.00    5
180.00         4
320000.00      4
120.00         3
45000.00       3
4200.71        2
5791.54        2
737205.85      2
677225.19      2
599496.44      2
1488169.21     2
432260.14      2
26840.83       2
811401.04      1
3843.55        1
9190.70        1
20844.72       1
542588.30      1
Name: count, dtype: int64

In [ ]:
df["surface"].sort_values(ascending=False).tail(30)

1292    32.82
1269    31.20
934     31.17
1015    30.25
591     27.60
11      25.93
212     24.39
1458    17.42
435     17.39
219     16.31
484     15.87
1417    15.00
1022    15.00
1311    15.00
1447    15.00
107     15.00
715     15.00
1413    15.00
671     15.00
309     12.00
1278    12.00
528     12.00
1042    12.00
1359    12.00
129     12.00
933     12.00
755      8.00
723      8.00
651      8.00
258      8.00
Name: surface, dtype: float64

In [ ]:
print(df.columns)